- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: grafana-lib-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: gluster-storage

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: grafana-log-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 4Gi
    storageClassName: gluster-storage
